CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_chat_id text UNIQUE,
    telegram_username text,
    full_name text,
    role text NOT NULL DEFAULT 'user',
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Repair legacy users tables that predate the current SQLAlchemy schema.
ALTER TABLE users ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE users ADD COLUMN IF NOT EXISTS telegram_chat_id text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS telegram_username text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS role text DEFAULT 'user';
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

UPDATE users SET role = 'user' WHERE role IS NULL;
UPDATE users SET is_active = true WHERE is_active IS NULL;
UPDATE users SET created_at = now() WHERE created_at IS NULL;
UPDATE users SET updated_at = now() WHERE updated_at IS NULL;

ALTER TABLE users ALTER COLUMN role SET DEFAULT 'user';
ALTER TABLE users ALTER COLUMN role SET NOT NULL;
ALTER TABLE users ALTER COLUMN is_active SET DEFAULT true;
ALTER TABLE users ALTER COLUMN is_active SET NOT NULL;
ALTER TABLE users ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE users ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE users ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE users ALTER COLUMN updated_at SET NOT NULL;

CREATE TABLE IF NOT EXISTS sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id text,
    name text NOT NULL,
    source_type text,
    url text,
    category text,
    priority text NOT NULL DEFAULT 'medium',
    check_frequency text NOT NULL DEFAULT 'weekly',
    responsible text,
    status text NOT NULL DEFAULT 'active',
    notes text,
    last_checked_at timestamptz,
    notion_page_id text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE sources ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE sources ADD COLUMN IF NOT EXISTS workspace_id text;
ALTER TABLE sources ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE sources ADD COLUMN IF NOT EXISTS source_type text;
ALTER TABLE sources ADD COLUMN IF NOT EXISTS url text;
ALTER TABLE sources ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE sources ADD COLUMN IF NOT EXISTS priority text DEFAULT 'medium';
ALTER TABLE sources ADD COLUMN IF NOT EXISTS check_frequency text DEFAULT 'weekly';
ALTER TABLE sources ADD COLUMN IF NOT EXISTS responsible text;
ALTER TABLE sources ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';
ALTER TABLE sources ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE sources ADD COLUMN IF NOT EXISTS last_checked_at timestamptz;
ALTER TABLE sources ADD COLUMN IF NOT EXISTS notion_page_id text;
ALTER TABLE sources ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE sources ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

UPDATE sources SET name = 'Legacy source' WHERE name IS NULL;
UPDATE sources SET workspace_id = 'default' WHERE workspace_id IS NULL;
UPDATE sources SET priority = 'medium' WHERE priority IS NULL;
UPDATE sources SET check_frequency = 'weekly' WHERE check_frequency IS NULL;
UPDATE sources SET status = 'active' WHERE status IS NULL;
UPDATE sources SET created_at = now() WHERE created_at IS NULL;
UPDATE sources SET updated_at = now() WHERE updated_at IS NULL;

ALTER TABLE sources ALTER COLUMN name SET NOT NULL;
ALTER TABLE sources ALTER COLUMN priority SET DEFAULT 'medium';
ALTER TABLE sources ALTER COLUMN priority SET NOT NULL;
ALTER TABLE sources ALTER COLUMN check_frequency SET DEFAULT 'weekly';
ALTER TABLE sources ALTER COLUMN check_frequency SET NOT NULL;
ALTER TABLE sources ALTER COLUMN status SET DEFAULT 'active';
ALTER TABLE sources ALTER COLUMN status SET NOT NULL;
ALTER TABLE sources ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE sources ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE sources ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE sources ALTER COLUMN updated_at SET NOT NULL;

CREATE TABLE IF NOT EXISTS source_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id text,
    source_id bigint REFERENCES sources(id) ON DELETE CASCADE,
    source_name text,
    source_type text NOT NULL DEFAULT 'web_search',
    source_provider text NOT NULL DEFAULT 'tavily',
    query text NOT NULL,
    external_url text,
    url text NOT NULL,
    title text NOT NULL,
    snippet text,
    content text,
    raw_text text,
    metrics_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    published_at timestamptz,
    score numeric,
    raw_json jsonb,
    collected_at timestamptz NOT NULL DEFAULT now(),
    ai_summary text,
    topics_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    offers_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    ctas_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    pains_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    objections_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    content_gaps_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    ideas_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    topic text,
    content_format text,
    offer text,
    cta text,
    audience_pain text,
    hook text,
    engagement_signals_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    risk_warning text,
    adaptation_idea text,
    tags_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    notion_page_id text,
    status text NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE source_items ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS workspace_id text;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS source_id bigint;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS source_name text;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS source_type text DEFAULT 'web_search';
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS source_provider text DEFAULT 'tavily';
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS query text;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS external_url text;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS url text;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS snippet text;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS content text;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS raw_text text;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS metrics_json jsonb DEFAULT '{}'::jsonb;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS published_at timestamptz;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS score numeric;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS raw_json jsonb;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS collected_at timestamptz DEFAULT now();
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS ai_summary text;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS topics_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS offers_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS ctas_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS pains_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS objections_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS content_gaps_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS ideas_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS topic text;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS content_format text;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS offer text;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS cta text;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS audience_pain text;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS hook text;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS engagement_signals_json jsonb DEFAULT '{}'::jsonb;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS risk_warning text;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS adaptation_idea text;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS tags_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS notion_page_id text;
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE source_items ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

UPDATE source_items SET source_type = 'web_search' WHERE source_type IS NULL;
UPDATE source_items SET workspace_id = 'default' WHERE workspace_id IS NULL;
UPDATE source_items SET source_provider = 'tavily' WHERE source_provider IS NULL;
UPDATE source_items SET query = 'legacy_import' WHERE query IS NULL;
UPDATE source_items SET title = 'Legacy source item ' || id::text WHERE title IS NULL;
UPDATE source_items SET url = COALESCE(external_url, '') WHERE url IS NULL;
UPDATE source_items SET content = raw_text WHERE content IS NULL AND raw_text IS NOT NULL;
UPDATE source_items SET metrics_json = '{}'::jsonb WHERE metrics_json IS NULL;
UPDATE source_items SET collected_at = now() WHERE collected_at IS NULL;
UPDATE source_items SET topics_json = '[]'::jsonb WHERE topics_json IS NULL;
UPDATE source_items SET offers_json = '[]'::jsonb WHERE offers_json IS NULL;
UPDATE source_items SET ctas_json = '[]'::jsonb WHERE ctas_json IS NULL;
UPDATE source_items SET pains_json = '[]'::jsonb WHERE pains_json IS NULL;
UPDATE source_items SET objections_json = '[]'::jsonb WHERE objections_json IS NULL;
UPDATE source_items SET content_gaps_json = '[]'::jsonb WHERE content_gaps_json IS NULL;
UPDATE source_items SET ideas_json = '[]'::jsonb WHERE ideas_json IS NULL;
UPDATE source_items SET engagement_signals_json = '{}'::jsonb WHERE engagement_signals_json IS NULL;
UPDATE source_items SET tags_json = '[]'::jsonb WHERE tags_json IS NULL;
UPDATE source_items SET status = 'active' WHERE status IS NULL;
UPDATE source_items SET created_at = now() WHERE created_at IS NULL;
UPDATE source_items SET updated_at = now() WHERE updated_at IS NULL;

ALTER TABLE source_items ALTER COLUMN source_type SET DEFAULT 'web_search';
ALTER TABLE source_items ALTER COLUMN source_type SET NOT NULL;
ALTER TABLE source_items ALTER COLUMN source_provider SET DEFAULT 'tavily';
ALTER TABLE source_items ALTER COLUMN source_provider SET NOT NULL;
ALTER TABLE source_items ALTER COLUMN query SET NOT NULL;
ALTER TABLE source_items ALTER COLUMN title SET NOT NULL;
ALTER TABLE source_items ALTER COLUMN url SET NOT NULL;
ALTER TABLE source_items ALTER COLUMN metrics_json SET DEFAULT '{}'::jsonb;
ALTER TABLE source_items ALTER COLUMN metrics_json SET NOT NULL;
ALTER TABLE source_items ALTER COLUMN collected_at SET DEFAULT now();
ALTER TABLE source_items ALTER COLUMN collected_at SET NOT NULL;
ALTER TABLE source_items ALTER COLUMN topics_json SET DEFAULT '[]'::jsonb;
ALTER TABLE source_items ALTER COLUMN topics_json SET NOT NULL;
ALTER TABLE source_items ALTER COLUMN offers_json SET DEFAULT '[]'::jsonb;
ALTER TABLE source_items ALTER COLUMN offers_json SET NOT NULL;
ALTER TABLE source_items ALTER COLUMN ctas_json SET DEFAULT '[]'::jsonb;
ALTER TABLE source_items ALTER COLUMN ctas_json SET NOT NULL;
ALTER TABLE source_items ALTER COLUMN pains_json SET DEFAULT '[]'::jsonb;
ALTER TABLE source_items ALTER COLUMN pains_json SET NOT NULL;
ALTER TABLE source_items ALTER COLUMN objections_json SET DEFAULT '[]'::jsonb;
ALTER TABLE source_items ALTER COLUMN objections_json SET NOT NULL;
ALTER TABLE source_items ALTER COLUMN content_gaps_json SET DEFAULT '[]'::jsonb;
ALTER TABLE source_items ALTER COLUMN content_gaps_json SET NOT NULL;
ALTER TABLE source_items ALTER COLUMN ideas_json SET DEFAULT '[]'::jsonb;
ALTER TABLE source_items ALTER COLUMN ideas_json SET NOT NULL;
ALTER TABLE source_items ALTER COLUMN engagement_signals_json SET DEFAULT '{}'::jsonb;
ALTER TABLE source_items ALTER COLUMN engagement_signals_json SET NOT NULL;
ALTER TABLE source_items ALTER COLUMN tags_json SET DEFAULT '[]'::jsonb;
ALTER TABLE source_items ALTER COLUMN tags_json SET NOT NULL;
ALTER TABLE source_items ALTER COLUMN status SET DEFAULT 'active';
ALTER TABLE source_items ALTER COLUMN status SET NOT NULL;
ALTER TABLE source_items ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE source_items ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE source_items ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE source_items ALTER COLUMN updated_at SET NOT NULL;

CREATE TABLE IF NOT EXISTS reviews_imports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id text,
    title text,
    source_name text,
    raw_text text,
    ai_summary text,
    pains_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    objections_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    content_ideas_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    repeated_questions_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    trust_issues_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    buying_triggers_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    emotional_words_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    customer_language_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    faq_ideas_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    risk_notes_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    recommended_posts_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    notion_page_id text,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE reviews_imports ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE reviews_imports ADD COLUMN IF NOT EXISTS workspace_id text;
ALTER TABLE reviews_imports ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE reviews_imports ADD COLUMN IF NOT EXISTS source_name text;
ALTER TABLE reviews_imports ADD COLUMN IF NOT EXISTS raw_text text;
ALTER TABLE reviews_imports ADD COLUMN IF NOT EXISTS ai_summary text;
ALTER TABLE reviews_imports ADD COLUMN IF NOT EXISTS pains_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ADD COLUMN IF NOT EXISTS objections_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ADD COLUMN IF NOT EXISTS content_ideas_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ADD COLUMN IF NOT EXISTS repeated_questions_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ADD COLUMN IF NOT EXISTS trust_issues_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ADD COLUMN IF NOT EXISTS buying_triggers_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ADD COLUMN IF NOT EXISTS emotional_words_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ADD COLUMN IF NOT EXISTS customer_language_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ADD COLUMN IF NOT EXISTS faq_ideas_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ADD COLUMN IF NOT EXISTS risk_notes_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ADD COLUMN IF NOT EXISTS recommended_posts_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ADD COLUMN IF NOT EXISTS notion_page_id text;
ALTER TABLE reviews_imports ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

UPDATE reviews_imports SET pains_json = '[]'::jsonb WHERE pains_json IS NULL;
UPDATE reviews_imports SET workspace_id = 'default' WHERE workspace_id IS NULL;
UPDATE reviews_imports SET objections_json = '[]'::jsonb WHERE objections_json IS NULL;
UPDATE reviews_imports SET content_ideas_json = '[]'::jsonb WHERE content_ideas_json IS NULL;
UPDATE reviews_imports SET repeated_questions_json = '[]'::jsonb WHERE repeated_questions_json IS NULL;
UPDATE reviews_imports SET trust_issues_json = '[]'::jsonb WHERE trust_issues_json IS NULL;
UPDATE reviews_imports SET buying_triggers_json = '[]'::jsonb WHERE buying_triggers_json IS NULL;
UPDATE reviews_imports SET emotional_words_json = '[]'::jsonb WHERE emotional_words_json IS NULL;
UPDATE reviews_imports SET customer_language_json = '[]'::jsonb WHERE customer_language_json IS NULL;
UPDATE reviews_imports SET faq_ideas_json = '[]'::jsonb WHERE faq_ideas_json IS NULL;
UPDATE reviews_imports SET risk_notes_json = '[]'::jsonb WHERE risk_notes_json IS NULL;
UPDATE reviews_imports SET recommended_posts_json = '[]'::jsonb WHERE recommended_posts_json IS NULL;
UPDATE reviews_imports SET created_at = now() WHERE created_at IS NULL;

ALTER TABLE reviews_imports ALTER COLUMN pains_json SET DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ALTER COLUMN pains_json SET NOT NULL;
ALTER TABLE reviews_imports ALTER COLUMN objections_json SET DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ALTER COLUMN objections_json SET NOT NULL;
ALTER TABLE reviews_imports ALTER COLUMN content_ideas_json SET DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ALTER COLUMN content_ideas_json SET NOT NULL;
ALTER TABLE reviews_imports ALTER COLUMN repeated_questions_json SET DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ALTER COLUMN repeated_questions_json SET NOT NULL;
ALTER TABLE reviews_imports ALTER COLUMN trust_issues_json SET DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ALTER COLUMN trust_issues_json SET NOT NULL;
ALTER TABLE reviews_imports ALTER COLUMN buying_triggers_json SET DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ALTER COLUMN buying_triggers_json SET NOT NULL;
ALTER TABLE reviews_imports ALTER COLUMN emotional_words_json SET DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ALTER COLUMN emotional_words_json SET NOT NULL;
ALTER TABLE reviews_imports ALTER COLUMN customer_language_json SET DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ALTER COLUMN customer_language_json SET NOT NULL;
ALTER TABLE reviews_imports ALTER COLUMN faq_ideas_json SET DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ALTER COLUMN faq_ideas_json SET NOT NULL;
ALTER TABLE reviews_imports ALTER COLUMN risk_notes_json SET DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ALTER COLUMN risk_notes_json SET NOT NULL;
ALTER TABLE reviews_imports ALTER COLUMN recommended_posts_json SET DEFAULT '[]'::jsonb;
ALTER TABLE reviews_imports ALTER COLUMN recommended_posts_json SET NOT NULL;
ALTER TABLE reviews_imports ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE reviews_imports ALTER COLUMN created_at SET NOT NULL;

CREATE TABLE IF NOT EXISTS content_plan (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publish_date timestamptz,
    channel text,
    content_type text,
    topic text,
    goal text,
    target_audience text,
    key_message text,
    cta text,
    source_idea text,
    why_recommended text,
    status text NOT NULL DEFAULT 'draft',
    notion_page_id text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE content_plan ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE content_plan ADD COLUMN IF NOT EXISTS publish_date timestamptz;
ALTER TABLE content_plan ADD COLUMN IF NOT EXISTS channel text;
ALTER TABLE content_plan ADD COLUMN IF NOT EXISTS content_type text;
ALTER TABLE content_plan ADD COLUMN IF NOT EXISTS topic text;
ALTER TABLE content_plan ADD COLUMN IF NOT EXISTS goal text;
ALTER TABLE content_plan ADD COLUMN IF NOT EXISTS target_audience text;
ALTER TABLE content_plan ADD COLUMN IF NOT EXISTS key_message text;
ALTER TABLE content_plan ADD COLUMN IF NOT EXISTS cta text;
ALTER TABLE content_plan ADD COLUMN IF NOT EXISTS source_idea text;
ALTER TABLE content_plan ADD COLUMN IF NOT EXISTS why_recommended text;
ALTER TABLE content_plan ADD COLUMN IF NOT EXISTS status text DEFAULT 'draft';
ALTER TABLE content_plan ADD COLUMN IF NOT EXISTS notion_page_id text;
ALTER TABLE content_plan ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE content_plan ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

UPDATE content_plan SET status = 'draft' WHERE status IS NULL;
UPDATE content_plan SET created_at = now() WHERE created_at IS NULL;
UPDATE content_plan SET updated_at = now() WHERE updated_at IS NULL;

ALTER TABLE content_plan ALTER COLUMN status SET DEFAULT 'draft';
ALTER TABLE content_plan ALTER COLUMN status SET NOT NULL;
ALTER TABLE content_plan ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE content_plan ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE content_plan ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE content_plan ALTER COLUMN updated_at SET NOT NULL;

CREATE TABLE IF NOT EXISTS drafts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_plan_id bigint REFERENCES content_plan(id) ON DELETE SET NULL,
    draft_type text,
    channel text,
    title text,
    draft_text text NOT NULL,
    version integer NOT NULL DEFAULT 1,
    status text NOT NULL DEFAULT 'pending',
    approved_by text,
    telegram_message_id text,
    notion_page_id text,
    ai_model text,
    prompt_name text,
    original_context_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    generation_metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE drafts ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS content_plan_id bigint;
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS draft_type text;
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS channel text;
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS draft_text text;
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS version integer DEFAULT 1;
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending';
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS approved_by text;
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS telegram_message_id text;
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS notion_page_id text;
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS ai_model text;
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS prompt_name text;
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS original_context_json jsonb DEFAULT '{}'::jsonb;
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS generation_metadata_json jsonb DEFAULT '{}'::jsonb;
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

UPDATE drafts SET draft_text = '' WHERE draft_text IS NULL;
UPDATE drafts SET version = 1 WHERE version IS NULL;
UPDATE drafts SET status = 'pending' WHERE status IS NULL;
UPDATE drafts SET original_context_json = '{}'::jsonb WHERE original_context_json IS NULL;
UPDATE drafts SET generation_metadata_json = '{}'::jsonb WHERE generation_metadata_json IS NULL;
UPDATE drafts SET created_at = now() WHERE created_at IS NULL;
UPDATE drafts SET updated_at = now() WHERE updated_at IS NULL;

ALTER TABLE drafts ALTER COLUMN draft_text SET NOT NULL;
ALTER TABLE drafts ALTER COLUMN version SET DEFAULT 1;
ALTER TABLE drafts ALTER COLUMN version SET NOT NULL;
ALTER TABLE drafts ALTER COLUMN status SET DEFAULT 'pending';
ALTER TABLE drafts ALTER COLUMN status SET NOT NULL;
ALTER TABLE drafts ALTER COLUMN original_context_json SET DEFAULT '{}'::jsonb;
ALTER TABLE drafts ALTER COLUMN original_context_json SET NOT NULL;
ALTER TABLE drafts ALTER COLUMN generation_metadata_json SET DEFAULT '{}'::jsonb;
ALTER TABLE drafts ALTER COLUMN generation_metadata_json SET NOT NULL;
ALTER TABLE drafts ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE drafts ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE drafts ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE drafts ALTER COLUMN updated_at SET NOT NULL;

CREATE TABLE IF NOT EXISTS approvals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_id bigint REFERENCES drafts(id) ON DELETE CASCADE,
    user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    action text,
    comment text,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE approvals ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE approvals ADD COLUMN IF NOT EXISTS draft_id bigint;
ALTER TABLE approvals ADD COLUMN IF NOT EXISTS user_id bigint;
ALTER TABLE approvals ADD COLUMN IF NOT EXISTS action text;
ALTER TABLE approvals ADD COLUMN IF NOT EXISTS comment text;
ALTER TABLE approvals ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

UPDATE approvals SET created_at = now() WHERE created_at IS NULL;
ALTER TABLE approvals ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE approvals ALTER COLUMN created_at SET NOT NULL;

CREATE TABLE IF NOT EXISTS reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_type text,
    title text,
    report_text text,
    body text,
    summary text,
    query text,
    sources_count integer NOT NULL DEFAULT 0,
    evidence_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    recommendations_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    raw_json jsonb,
    week_start date,
    week_end date,
    status text NOT NULL DEFAULT 'ready',
    notion_page_id text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE reports ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS report_type text;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS report_text text;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS body text;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS summary text;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS query text;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS sources_count integer DEFAULT 0;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS evidence_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS recommendations_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS raw_json jsonb;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS week_start date;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS week_end date;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS status text DEFAULT 'ready';
ALTER TABLE reports ADD COLUMN IF NOT EXISTS notion_page_id text;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE reports ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

UPDATE reports SET body = report_text WHERE body IS NULL AND report_text IS NOT NULL;
UPDATE reports SET sources_count = 0 WHERE sources_count IS NULL;
UPDATE reports SET evidence_json = '[]'::jsonb WHERE evidence_json IS NULL;
UPDATE reports SET status = 'ready' WHERE status IS NULL;
UPDATE reports SET recommendations_json = '[]'::jsonb WHERE recommendations_json IS NULL;
UPDATE reports SET created_at = now() WHERE created_at IS NULL;
UPDATE reports SET updated_at = now() WHERE updated_at IS NULL;
ALTER TABLE reports ALTER COLUMN sources_count SET DEFAULT 0;
ALTER TABLE reports ALTER COLUMN sources_count SET NOT NULL;
ALTER TABLE reports ALTER COLUMN evidence_json SET DEFAULT '[]'::jsonb;
ALTER TABLE reports ALTER COLUMN evidence_json SET NOT NULL;
ALTER TABLE reports ALTER COLUMN status SET DEFAULT 'ready';
ALTER TABLE reports ALTER COLUMN status SET NOT NULL;
ALTER TABLE reports ALTER COLUMN recommendations_json SET DEFAULT '[]'::jsonb;
ALTER TABLE reports ALTER COLUMN recommendations_json SET NOT NULL;
ALTER TABLE reports ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE reports ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE reports ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE reports ALTER COLUMN updated_at SET NOT NULL;

CREATE TABLE IF NOT EXISTS market_scan_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    status text NOT NULL DEFAULT 'running',
    current_step text,
    query text,
    sources_count integer NOT NULL DEFAULT 0,
    report_id bigint REFERENCES reports(id) ON DELETE SET NULL,
    error_message text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE market_scan_jobs ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE market_scan_jobs ADD COLUMN IF NOT EXISTS user_id bigint;
ALTER TABLE market_scan_jobs ADD COLUMN IF NOT EXISTS workspace_id text;
ALTER TABLE market_scan_jobs ADD COLUMN IF NOT EXISTS status text DEFAULT 'running';
ALTER TABLE market_scan_jobs ADD COLUMN IF NOT EXISTS current_step text;
ALTER TABLE market_scan_jobs ADD COLUMN IF NOT EXISTS query text;
ALTER TABLE market_scan_jobs ADD COLUMN IF NOT EXISTS sources_count integer DEFAULT 0;
ALTER TABLE market_scan_jobs ADD COLUMN IF NOT EXISTS report_id bigint;
ALTER TABLE market_scan_jobs ADD COLUMN IF NOT EXISTS error_message text;
ALTER TABLE market_scan_jobs ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE market_scan_jobs ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

UPDATE market_scan_jobs SET status = 'running' WHERE status IS NULL;
UPDATE market_scan_jobs SET sources_count = 0 WHERE sources_count IS NULL;
UPDATE market_scan_jobs SET created_at = now() WHERE created_at IS NULL;
UPDATE market_scan_jobs SET updated_at = now() WHERE updated_at IS NULL;
ALTER TABLE market_scan_jobs ALTER COLUMN status SET DEFAULT 'running';
ALTER TABLE market_scan_jobs ALTER COLUMN status SET NOT NULL;
ALTER TABLE market_scan_jobs ALTER COLUMN sources_count SET DEFAULT 0;
ALTER TABLE market_scan_jobs ALTER COLUMN sources_count SET NOT NULL;
ALTER TABLE market_scan_jobs ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE market_scan_jobs ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE market_scan_jobs ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE market_scan_jobs ALTER COLUMN updated_at SET NOT NULL;

CREATE TABLE IF NOT EXISTS publications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_id bigint REFERENCES drafts(id) ON DELETE SET NULL,
    channel text,
    status text NOT NULL DEFAULT 'ready',
    published_url text,
    published_at timestamptz,
    scheduled_for timestamptz,
    telegram_message_id text,
    views integer,
    reactions integer,
    comments_count integer,
    clicks integer,
    leads integer,
    notes text,
    metrics_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE publications ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS draft_id bigint;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS channel text;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS status text DEFAULT 'ready';
ALTER TABLE publications ADD COLUMN IF NOT EXISTS published_url text;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS published_at timestamptz;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS scheduled_for timestamptz;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS telegram_message_id text;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS views integer;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS reactions integer;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS comments_count integer;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS clicks integer;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS leads integer;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS metrics_json jsonb DEFAULT '{}'::jsonb;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE publications ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();
ALTER TABLE publications ADD COLUMN IF NOT EXISTS workspace_id text;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS content_item_id bigint;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS platform text;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS provider text;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS account_id text;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS page_id text;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS scheduled_time timestamptz;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS external_submission_id text;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS external_post_url text;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS error_message text;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS metadata_json jsonb DEFAULT '{}'::jsonb;

UPDATE publications SET metadata_json = '{}'::jsonb WHERE metadata_json IS NULL;
ALTER TABLE publications ALTER COLUMN metadata_json SET DEFAULT '{}'::jsonb;
ALTER TABLE publications ALTER COLUMN metadata_json SET NOT NULL;

UPDATE publications SET status = 'ready' WHERE status IS NULL;
UPDATE publications SET metrics_json = '{}'::jsonb WHERE metrics_json IS NULL;
UPDATE publications SET created_at = now() WHERE created_at IS NULL;
UPDATE publications SET updated_at = now() WHERE updated_at IS NULL;
ALTER TABLE publications ALTER COLUMN status SET DEFAULT 'ready';
ALTER TABLE publications ALTER COLUMN status SET NOT NULL;
ALTER TABLE publications ALTER COLUMN metrics_json SET DEFAULT '{}'::jsonb;
ALTER TABLE publications ALTER COLUMN metrics_json SET NOT NULL;
ALTER TABLE publications ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE publications ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE publications ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE publications ALTER COLUMN updated_at SET NOT NULL;

CREATE TABLE IF NOT EXISTS integrations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id text,
    provider text NOT NULL,
    enabled boolean NOT NULL DEFAULT false,
    status text,
    api_key_encrypted text,
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    last_checked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_integrations_workspace_provider
    ON integrations(COALESCE(workspace_id, ''), provider);

CREATE TABLE IF NOT EXISTS social_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id text,
    provider text NOT NULL,
    platform text,
    external_account_id text,
    display_name text,
    username text,
    status text NOT NULL DEFAULT 'connected',
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_social_accounts_workspace_provider_account
    ON social_accounts(COALESCE(workspace_id, ''), provider, COALESCE(external_account_id, ''));

ALTER TABLE social_accounts ADD COLUMN IF NOT EXISTS connection_request_id bigint;
ALTER TABLE social_accounts ADD COLUMN IF NOT EXISTS connected_at timestamptz;
ALTER TABLE social_accounts ADD COLUMN IF NOT EXISTS last_checked_at timestamptz;

CREATE TABLE IF NOT EXISTS social_connection_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id text,
    user_email text,
    platform text NOT NULL DEFAULT 'instagram',
    requested_username text,
    status text NOT NULL DEFAULT 'pending',
    admin_note text,
    user_note text,
    resolved_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_social_connection_requests_workspace
    ON social_connection_requests(COALESCE(workspace_id, ''));
CREATE INDEX IF NOT EXISTS idx_social_connection_requests_status
    ON social_connection_requests(status);

ALTER TABLE social_connection_requests ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE social_connection_requests ADD COLUMN IF NOT EXISTS workspace_id text;
ALTER TABLE social_connection_requests ADD COLUMN IF NOT EXISTS user_email text;
ALTER TABLE social_connection_requests ADD COLUMN IF NOT EXISTS platform text DEFAULT 'instagram';
ALTER TABLE social_connection_requests ADD COLUMN IF NOT EXISTS requested_username text;
ALTER TABLE social_connection_requests ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending';
ALTER TABLE social_connection_requests ADD COLUMN IF NOT EXISTS admin_note text;
ALTER TABLE social_connection_requests ADD COLUMN IF NOT EXISTS user_note text;
ALTER TABLE social_connection_requests ADD COLUMN IF NOT EXISTS resolved_at timestamptz;
ALTER TABLE social_connection_requests ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE social_connection_requests ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS publication_targets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id text,
    platform text NOT NULL,
    provider text NOT NULL DEFAULT 'blotato',
    account_id text,
    page_id text,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_publication_targets_workspace_platform
    ON publication_targets(COALESCE(workspace_id, ''), platform, provider);

CREATE TABLE IF NOT EXISTS manual_publish_packages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id text,
    draft_id bigint REFERENCES drafts(id) ON DELETE SET NULL,
    platform text NOT NULL,
    caption text,
    hook text,
    script text,
    visual_brief text,
    hashtags text,
    cta text,
    status text NOT NULL DEFAULT 'ready',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_manual_packages_draft ON manual_publish_packages(draft_id);

ALTER TABLE integrations ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE integrations ADD COLUMN IF NOT EXISTS workspace_id text;
ALTER TABLE integrations ADD COLUMN IF NOT EXISTS provider text;
ALTER TABLE integrations ADD COLUMN IF NOT EXISTS enabled boolean DEFAULT false;
ALTER TABLE integrations ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE integrations ADD COLUMN IF NOT EXISTS api_key_encrypted text;
ALTER TABLE integrations ADD COLUMN IF NOT EXISTS metadata_json jsonb DEFAULT '{}'::jsonb;
ALTER TABLE integrations ADD COLUMN IF NOT EXISTS last_checked_at timestamptz;
ALTER TABLE integrations ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE integrations ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

ALTER TABLE social_accounts ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE social_accounts ADD COLUMN IF NOT EXISTS workspace_id text;
ALTER TABLE social_accounts ADD COLUMN IF NOT EXISTS provider text;
ALTER TABLE social_accounts ADD COLUMN IF NOT EXISTS platform text;
ALTER TABLE social_accounts ADD COLUMN IF NOT EXISTS external_account_id text;
ALTER TABLE social_accounts ADD COLUMN IF NOT EXISTS display_name text;
ALTER TABLE social_accounts ADD COLUMN IF NOT EXISTS username text;
ALTER TABLE social_accounts ADD COLUMN IF NOT EXISTS status text DEFAULT 'connected';
ALTER TABLE social_accounts ADD COLUMN IF NOT EXISTS metadata_json jsonb DEFAULT '{}'::jsonb;
ALTER TABLE social_accounts ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE social_accounts ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

ALTER TABLE publication_targets ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE publication_targets ADD COLUMN IF NOT EXISTS workspace_id text;
ALTER TABLE publication_targets ADD COLUMN IF NOT EXISTS platform text;
ALTER TABLE publication_targets ADD COLUMN IF NOT EXISTS provider text DEFAULT 'blotato';
ALTER TABLE publication_targets ADD COLUMN IF NOT EXISTS account_id text;
ALTER TABLE publication_targets ADD COLUMN IF NOT EXISTS page_id text;
ALTER TABLE publication_targets ADD COLUMN IF NOT EXISTS enabled boolean DEFAULT true;
ALTER TABLE publication_targets ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE publication_targets ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

ALTER TABLE manual_publish_packages ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE manual_publish_packages ADD COLUMN IF NOT EXISTS workspace_id text;
ALTER TABLE manual_publish_packages ADD COLUMN IF NOT EXISTS draft_id bigint;
ALTER TABLE manual_publish_packages ADD COLUMN IF NOT EXISTS platform text;
ALTER TABLE manual_publish_packages ADD COLUMN IF NOT EXISTS caption text;
ALTER TABLE manual_publish_packages ADD COLUMN IF NOT EXISTS hook text;
ALTER TABLE manual_publish_packages ADD COLUMN IF NOT EXISTS script text;
ALTER TABLE manual_publish_packages ADD COLUMN IF NOT EXISTS visual_brief text;
ALTER TABLE manual_publish_packages ADD COLUMN IF NOT EXISTS hashtags text;
ALTER TABLE manual_publish_packages ADD COLUMN IF NOT EXISTS cta text;
ALTER TABLE manual_publish_packages ADD COLUMN IF NOT EXISTS status text DEFAULT 'ready';
ALTER TABLE manual_publish_packages ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE manual_publish_packages ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS app_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level text,
    module text,
    message text,
    details_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE app_logs ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE app_logs ADD COLUMN IF NOT EXISTS level text;
ALTER TABLE app_logs ADD COLUMN IF NOT EXISTS module text;
ALTER TABLE app_logs ADD COLUMN IF NOT EXISTS message text;
ALTER TABLE app_logs ADD COLUMN IF NOT EXISTS details_json jsonb DEFAULT '{}'::jsonb;
ALTER TABLE app_logs ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

UPDATE app_logs SET details_json = '{}'::jsonb WHERE details_json IS NULL;
UPDATE app_logs SET created_at = now() WHERE created_at IS NULL;
ALTER TABLE app_logs ALTER COLUMN details_json SET DEFAULT '{}'::jsonb;
ALTER TABLE app_logs ALTER COLUMN details_json SET NOT NULL;
ALTER TABLE app_logs ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE app_logs ALTER COLUMN created_at SET NOT NULL;

CREATE TABLE IF NOT EXISTS settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key text UNIQUE NOT NULL,
    value text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE settings ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS key text;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS value text;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE settings ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

UPDATE settings
SET key = 'legacy_setting_' || id::text
WHERE key IS NULL;
UPDATE settings SET created_at = now() WHERE created_at IS NULL;
UPDATE settings SET updated_at = now() WHERE updated_at IS NULL;
ALTER TABLE settings ALTER COLUMN key SET NOT NULL;
ALTER TABLE settings ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE settings ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE settings ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE settings ALTER COLUMN updated_at SET NOT NULL;

-- ============================================================
-- Workspace / team access control (multi-tenant foundation)
-- ============================================================

-- Scope core content to a workspace. Existing rows belong to the single
-- legacy client, so backfill them to the 'default' workspace.
ALTER TABLE reports ADD COLUMN IF NOT EXISTS workspace_id text;
ALTER TABLE content_plan ADD COLUMN IF NOT EXISTS workspace_id text;
ALTER TABLE drafts ADD COLUMN IF NOT EXISTS workspace_id text;
UPDATE reports SET workspace_id = 'default' WHERE workspace_id IS NULL;
UPDATE content_plan SET workspace_id = 'default' WHERE workspace_id IS NULL;
UPDATE drafts SET workspace_id = 'default' WHERE workspace_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_reports_workspace ON reports(workspace_id);
CREATE INDEX IF NOT EXISTS idx_content_plan_workspace ON content_plan(workspace_id);
CREATE INDEX IF NOT EXISTS idx_drafts_workspace ON drafts(workspace_id);
CREATE INDEX IF NOT EXISTS idx_sources_workspace ON sources(workspace_id);
CREATE INDEX IF NOT EXISTS idx_source_items_workspace ON source_items(workspace_id);
CREATE INDEX IF NOT EXISTS idx_reviews_imports_workspace ON reviews_imports(workspace_id);

CREATE TABLE IF NOT EXISTS workspace_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id text NOT NULL,
    user_id bigint,
    email text NOT NULL,
    role text NOT NULL DEFAULT 'viewer',
    status text NOT NULL DEFAULT 'active',
    invited_by text,
    invited_at timestamptz,
    joined_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE workspace_members ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE workspace_members ADD COLUMN IF NOT EXISTS workspace_id text;
ALTER TABLE workspace_members ADD COLUMN IF NOT EXISTS user_id bigint;
ALTER TABLE workspace_members ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE workspace_members ADD COLUMN IF NOT EXISTS role text DEFAULT 'viewer';
ALTER TABLE workspace_members ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';
ALTER TABLE workspace_members ADD COLUMN IF NOT EXISTS invited_by text;
ALTER TABLE workspace_members ADD COLUMN IF NOT EXISTS invited_at timestamptz;
ALTER TABLE workspace_members ADD COLUMN IF NOT EXISTS joined_at timestamptz;
ALTER TABLE workspace_members ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE workspace_members ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();
CREATE UNIQUE INDEX IF NOT EXISTS uq_workspace_members_ws_email
    ON workspace_members(workspace_id, lower(email));
CREATE INDEX IF NOT EXISTS idx_workspace_members_email ON workspace_members(lower(email));

CREATE TABLE IF NOT EXISTS workspace_invitations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id text NOT NULL,
    email text NOT NULL,
    role text NOT NULL DEFAULT 'viewer',
    token text UNIQUE NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    invited_by text,
    expires_at timestamptz,
    accepted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE workspace_invitations ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE workspace_invitations ADD COLUMN IF NOT EXISTS workspace_id text;
ALTER TABLE workspace_invitations ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE workspace_invitations ADD COLUMN IF NOT EXISTS role text DEFAULT 'viewer';
ALTER TABLE workspace_invitations ADD COLUMN IF NOT EXISTS token text;
ALTER TABLE workspace_invitations ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending';
ALTER TABLE workspace_invitations ADD COLUMN IF NOT EXISTS invited_by text;
ALTER TABLE workspace_invitations ADD COLUMN IF NOT EXISTS expires_at timestamptz;
ALTER TABLE workspace_invitations ADD COLUMN IF NOT EXISTS accepted_at timestamptz;
ALTER TABLE workspace_invitations ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE workspace_invitations ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();
CREATE INDEX IF NOT EXISTS idx_workspace_invitations_token ON workspace_invitations(token);
CREATE INDEX IF NOT EXISTS idx_workspace_invitations_email ON workspace_invitations(lower(email));

CREATE TABLE IF NOT EXISTS share_links (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id text NOT NULL,
    resource_type text NOT NULL,
    resource_id bigint,
    token text UNIQUE NOT NULL,
    access_level text NOT NULL DEFAULT 'view',
    password_hash text,
    expires_at timestamptz,
    is_active boolean NOT NULL DEFAULT true,
    created_by text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE share_links ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE share_links ADD COLUMN IF NOT EXISTS workspace_id text;
ALTER TABLE share_links ADD COLUMN IF NOT EXISTS resource_type text;
ALTER TABLE share_links ADD COLUMN IF NOT EXISTS resource_id bigint;
ALTER TABLE share_links ADD COLUMN IF NOT EXISTS token text;
ALTER TABLE share_links ADD COLUMN IF NOT EXISTS access_level text DEFAULT 'view';
ALTER TABLE share_links ADD COLUMN IF NOT EXISTS password_hash text;
ALTER TABLE share_links ADD COLUMN IF NOT EXISTS expires_at timestamptz;
ALTER TABLE share_links ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE share_links ADD COLUMN IF NOT EXISTS created_by text;
ALTER TABLE share_links ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE share_links ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();
CREATE INDEX IF NOT EXISTS idx_share_links_token ON share_links(token);

CREATE TABLE IF NOT EXISTS content_tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id text NOT NULL,
    source_type text NOT NULL DEFAULT 'manual',
    source_id bigint,
    title text NOT NULL,
    description text,
    assignee_email text,
    status text NOT NULL DEFAULT 'todo',
    priority text NOT NULL DEFAULT 'medium',
    due_date date,
    created_by text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE content_tasks ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE content_tasks ADD COLUMN IF NOT EXISTS workspace_id text;
ALTER TABLE content_tasks ADD COLUMN IF NOT EXISTS source_type text DEFAULT 'manual';
ALTER TABLE content_tasks ADD COLUMN IF NOT EXISTS source_id bigint;
ALTER TABLE content_tasks ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE content_tasks ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE content_tasks ADD COLUMN IF NOT EXISTS assignee_email text;
ALTER TABLE content_tasks ADD COLUMN IF NOT EXISTS status text DEFAULT 'todo';
ALTER TABLE content_tasks ADD COLUMN IF NOT EXISTS priority text DEFAULT 'medium';
ALTER TABLE content_tasks ADD COLUMN IF NOT EXISTS due_date date;
ALTER TABLE content_tasks ADD COLUMN IF NOT EXISTS created_by text;
ALTER TABLE content_tasks ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE content_tasks ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();
CREATE INDEX IF NOT EXISTS idx_content_tasks_workspace ON content_tasks(workspace_id);
CREATE INDEX IF NOT EXISTS idx_content_tasks_status ON content_tasks(status);

-- Video credits for pay-per-video AI generation (Replicate provider). Credits
-- are granted by the frontend Polar webhook on a paid credit-pack order and
-- consumed (reserved, then settled or refunded) by the backend. Both sides key
-- on workspace_id, which equals the Supabase user id in the authenticated path.
CREATE TABLE IF NOT EXISTS video_credits (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id text NOT NULL,
    balance integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE video_credits ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE video_credits ADD COLUMN IF NOT EXISTS workspace_id text;
ALTER TABLE video_credits ADD COLUMN IF NOT EXISTS balance integer DEFAULT 0;
ALTER TABLE video_credits ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE video_credits ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();
CREATE UNIQUE INDEX IF NOT EXISTS uq_video_credits_workspace ON video_credits(workspace_id);

CREATE TABLE IF NOT EXISTS video_generations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id text NOT NULL,
    provider text NOT NULL DEFAULT 'replicate',
    kind text NOT NULL DEFAULT 'video',
    prediction_id text,
    status text NOT NULL DEFAULT 'starting',
    credits_charged integer NOT NULL DEFAULT 0,
    refunded boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE video_generations ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE video_generations ADD COLUMN IF NOT EXISTS workspace_id text;
ALTER TABLE video_generations ADD COLUMN IF NOT EXISTS provider text DEFAULT 'replicate';
ALTER TABLE video_generations ADD COLUMN IF NOT EXISTS kind text DEFAULT 'video';
ALTER TABLE video_generations ADD COLUMN IF NOT EXISTS prediction_id text;
ALTER TABLE video_generations ADD COLUMN IF NOT EXISTS status text DEFAULT 'starting';
ALTER TABLE video_generations ADD COLUMN IF NOT EXISTS credits_charged integer DEFAULT 0;
ALTER TABLE video_generations ADD COLUMN IF NOT EXISTS refunded boolean DEFAULT false;
ALTER TABLE video_generations ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE video_generations ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();
CREATE UNIQUE INDEX IF NOT EXISTS uq_video_generations_prediction
    ON video_generations(prediction_id)
    WHERE prediction_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_video_generations_workspace ON video_generations(workspace_id);

CREATE INDEX IF NOT EXISTS idx_source_items_source_id ON source_items(source_id);
CREATE INDEX IF NOT EXISTS idx_source_items_collected_at ON source_items(collected_at DESC);
CREATE INDEX IF NOT EXISTS idx_source_items_query ON source_items(query);
CREATE INDEX IF NOT EXISTS idx_source_items_source_provider ON source_items(source_provider);
CREATE INDEX IF NOT EXISTS idx_source_items_created_at ON source_items(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_source_items_url ON source_items(url);
CREATE INDEX IF NOT EXISTS idx_content_plan_publish_date ON content_plan(publish_date);
CREATE INDEX IF NOT EXISTS idx_drafts_status ON drafts(status);
CREATE INDEX IF NOT EXISTS idx_reports_type_created ON reports(report_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_market_scan_jobs_user_created
    ON market_scan_jobs(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_market_scan_jobs_status ON market_scan_jobs(status);
CREATE INDEX IF NOT EXISTS idx_publications_status ON publications(status);
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = current_schema()
          AND indexname = 'uq_publications_draft_channel'
    ) AND NOT EXISTS (
        SELECT 1
        FROM publications
        WHERE draft_id IS NOT NULL
          AND channel IS NOT NULL
        GROUP BY draft_id, channel
        HAVING count(*) > 1
    ) THEN
        CREATE UNIQUE INDEX uq_publications_draft_channel
            ON publications(draft_id, channel)
            WHERE draft_id IS NOT NULL;
    END IF;
END;
$$;
CREATE INDEX IF NOT EXISTS idx_app_logs_created_at ON app_logs(created_at DESC);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
    table_name text;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'users', 'sources', 'source_items', 'content_plan', 'drafts', 'reports',
        'market_scan_jobs', 'publications', 'settings', 'integrations',
        'social_accounts', 'publication_targets', 'manual_publish_packages',
        'workspace_members', 'workspace_invitations', 'share_links',
        'content_tasks', 'video_credits', 'video_generations'
    ]
    LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS trg_%I_updated_at ON %I', table_name, table_name);
        EXECUTE format(
            'CREATE TRIGGER trg_%I_updated_at BEFORE UPDATE ON %I '
            'FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
            table_name,
            table_name
        );
    END LOOP;
END;
$$;
