from enum import IntEnum


class BotState(IntEnum):
    WAITING_POST = 1
    WAITING_CASE = 2
    WAITING_REVIEWS = 3
    ADD_SOURCE_NAME = 10
    ADD_SOURCE_TYPE = 11
    ADD_SOURCE_URL = 12
    ADD_SOURCE_CATEGORY = 13
    ADD_SOURCE_PRIORITY = 14
    ADD_SOURCE_FREQUENCY = 15
    DISABLE_SOURCE = 20
    IMPORT_SOURCE_SELECT = 30
    IMPORT_SOURCE_TEXT = 31
    PLAN_GOAL = 40
    PLAN_AUDIENCE = 41
    PLAN_OFFER = 42
    PLAN_CHANNELS = 43
    PLAN_INTENSITY = 44
    PLAN_ITEM_SELECT = 50
    METRICS_PUBLICATION_SELECT = 60
    METRICS_VALUES = 61
    WEB_SEARCH_QUERY = 70
    MARKET_SCAN_NICHE = 71
    MARKET_SCAN_REGION = 72
    MARKET_SCAN_COMPETITORS = 73
    COMPETITOR_REPORT_TOPIC = 74
    DISCOVER_SOURCES_NICHE = 80
    DISCOVER_SOURCES_REGION = 81
    DISCOVER_SOURCES_PLATFORMS = 82
    EDIT_DRAFT_TEXT = 90
    SCHEDULE_DATETIME = 91
